// gs-web-app/gs-web-app/src/app/components/Header/Header.jsx
import * as React from 'react';
import Logo from '../../../assets/img/kpi-logo-black.png';
import styles from './Header.module.scss';
import {Link} from 'react-router-dom';
import {connect} from 'react-redux';
import {createStructuredSelector} from 'reselect';

import AccountCircleRounded from '@material-ui/icons/AccountCircleRounded';
import ExitToApp from '@material-ui/icons/ExitToApp';
import IconButton from '@material-ui/core/IconButton';
import Button from '@material-ui/core/Button';
import {makeSelectUserData} from '../../state/selectors/user';

import {Routes} from '../../consts/routePaths'
import authService from '../../services/authService';


const mapStateToProps = createStructuredSelector({
    userData: makeSelectUserData(),
});

const HeaderComponent = ({userData}) => {
    const {name} = userData || {};
    const isLoggedIn = !!userData;

    return (
        <div className={styles.Header}>
            <Link to={Routes.HOME} className={styles.Header__logo}>
                <Button>
                    <img src={Logo} alt="logo"/>
                    Аспірантура КПІ
                </Button>
            </Link>

            {
                isLoggedIn &&
                <div className={styles.Header__logged}>
                <span className={styles.Header_userName}>
                     Вітаємо, {name}
                </span>
                    <Link to={Routes.HOME} className={styles.Header__logged_icon}>
                        <IconButton
                            color="inherit"
                            aria-label="upload picture"
                            component="span"
                        >
                            <AccountCircleRounded/>
                        </IconButton>
                    </Link>
                    <IconButton
                        color="inherit"
                        aria-label="upload picture"
                        component="span"
                        onClick={authService.logout}
                    >
                        <ExitToApp/>
                    </IconButton>
                </div>
            }
        </div>
    )
};

export default connect(mapStateToProps)(HeaderComponent);

// ng-app/src/app/core/components/header/header.component.ts
import { Component } from '@angular/core';
import { Observable } from 'rxjs';
import { AuthService } from '../../auth/auth.service';
import { IUser } from '../../auth/user-inteface';

@Component({
  selector: 'ak-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent {
  public isLoggedIn$: Observable<boolean>;
  public user$: Observable<IUser>;

  constructor(private _authService: AuthService) {
    this.isLoggedIn$ = this._authService.isLoggedIn$;
    this.user$ = this._authService.getUserData$();
  }

  public logout(): void {
    this._authService.logout();
  }
}

<nav class="header">
  <a routerLink="/" mat-button>
    <img class="header__logo" src="assets/images/kpi-logo-black.png" alt="KPI">
    Аспірантура КПІ
  </a>
  <div class="flex-spacer"></div>
  <span *ngIf="isLoggedIn$ | async">
    Вітаємо, <span *ngIf="user$ | async">{{ (user$ | async)?.first_name + ' ' + (user$ | async)?.last_name }}</span>
  </span>
  <a routerLink="/cabinet" mat-icon-button>
    <mat-icon>account_circle</mat-icon>
  </a>
  <button *ngIf="isLoggedIn$ | async" mat-icon-button (click)="logout()">
    <mat-icon>exit_to_app</mat-icon>
  </button>
</nav>
